longDescription = """
Renames at-rules such as `@keyframes`. This can be potentially unsafe if other
JS/CSS files need to read this definition.
"""

inputExample = """
@keyframes fadeOut {
    from {
        opacity: 1;
    }
    to {
        opacity: 0;
    }
}
.box {
    animation-name: fadeOut;
}
"""

outputExample = """
@keyframes a {
    from {
        opacity: 1;
    }
    to {
        opacity: 0;
    }
}
.box {
    animation-name: a;
}
"""

safe = 2 # Changes semantics
